# 根据七尺宇教程修改
#来源https://github.com/qichiyuhub/rule
# 必读！！！
# 此版本没有做防泄露处理，如介意请使用另一个名字为configdns的版本
# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 跑裸核用户请自行去掉下方控制面板模块的注释。
# 机场订阅
proxy-providers:    
  机场名:
    url: "机场订阅链接"
    type: http
    interval: 21600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 60
    proxy: Direct
    
# 节点信息
proxies:
  - {name: Direct, type: direct}
  - {name: Reject, type: reject}
# 全局配置 
mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
#global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true
# 为防止使用插件朋友遇到面板问题，我注释掉了此模块。
external-controller: 0.0.0.0:9090
secret: "123456"
external-ui: ui
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
# 嗅探（fakeip下其实可以不用嗅探）
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
# 入站
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #使用nikki，混入全部不修改的情况，开启接口指定为nikki
  #device: nikki
  #使用仅内核自行修改下面三项为true
  auto-route: true
  auto-redirect: true
  auto-detect-interface: false
# DNS模块
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.8.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:fakeipfilter_domain"
  default-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
# 策略组定义
pr: &pr 
  type: select
  proxies:
    - 默认代理
    - 🔯 香港故转
    - 🔯 台湾故转
    - 🔯 日本故转
    - 🔯 新加坡故转
    - 🔯 美国故转
    - 🏡 家宽节点
    - 🧑‍🦽 低倍节点
    - ♻️ 全部自动
    - 🌐 全部手动
    - Direct
    - Reject
proxy-groups:
  # 策略分流组
  - {name: 默认代理, type: select, proxies: [🔯 香港故转, 🔯 台湾故转, 🔯 日本故转, 🔯 新加坡故转, 🔯 美国故转, 🏡 家宽节点, 🧑‍🦽 低倍节点, ♻️ 全部自动, 🌐 全部手动, Direct, Reject]}
  # 应用分流组
  - {name: YouTube, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/YouTube.png"}
  - {name: Google, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Google.png"}
  - {name: AI, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/ChatGPT.png"}
  - {name: GitHub, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/GitHub.png"}
  - {name: Apple, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Apple_black.png"}
  - {name: Microsoft, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Microsoft.png"}
  - {name: TikTok, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/TikTok.png"}
  - {name: Telegram, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Telegram.png"}
  - {name: PayPal, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/PayPal.png"}
  - {name: NETFLIX, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Netflix.png"}
  - {name: TMDB, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/tmdb.png"}
  - {name: Steam, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Steam.png"}
  - {name: Game, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Game.png"}
  - {name: 广告拦截, type: select, proxies: [Reject], icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Adblock.png"}
  - {name: 漏网之鱼, <<: *pr,icon: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/yq487900/Icon/main/large/Global.png"}
  # 代理分组
  # 香港组
  - {name: 🔯 香港故转, type: fallback, interval: 60, lazy: false, proxies: [🇭🇰 香港手动, ♻️ 香港自动]}
  - {name: ♻️ 香港自动, type: url-test, include-all: true, tolerance: 20, interval: 60, filter: "(?=.*(广港|香港|HK|Hong Kong|🇭🇰|HongKong)).*$"}
  - {name: 🇭🇰 香港手动, type: select, include-all: true, filter: "(?=.*(广港|香港|HK|Hong Kong|🇭🇰|HongKong)).*$"}
  # 台湾组
  - {name: 🔯 台湾故转, type: fallback, interval: 60, lazy: false, proxies: [🇹🇼 台湾手动, ♻️ 台湾自动]}
  - {name: ♻️ 台湾自动, type: url-test, include-all: true, tolerance: 20, interval: 60, filter: "(?=.*(广台|台湾|台灣|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan)).*$"}
  - {name: 🇹🇼 台湾手动, type: select, include-all: true, filter: "(?=.*(广台|台湾|台灣|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan)).*$"}
  # 日本组
  - {name: 🔯 日本故转, type: fallback, interval: 60, lazy: false, proxies: [🇯🇵 日本手动, ♻️ 日本自动]}
  - {name: ♻️ 日本自动, type: url-test, include-all: true, tolerance: 20, interval: 60, filter: "(?=.*(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)).*$"}
  - {name: 🇯🇵 日本手动, type: select, include-all: true, filter: "(?=.*(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)).*$"}
  # 新加坡组
  - {name: 🔯 新加坡故转, type: fallback, interval: 60, lazy: false, proxies: [🇸🇬 新加坡手动, ♻️ 新加坡自动]}
  - {name: ♻️ 新加坡自动, type: url-test, include-all: true, tolerance: 20, interval: 60, filter: "(?=.*(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)).*$"}
  - {name: 🇸🇬 新加坡手动, type: select, include-all: true, filter: "(?=.*(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)).*$"}
  # 美国组
  - {name: 🔯 美国故转, type: fallback, interval: 60, lazy: false, proxies: [🇺🇲 美国手动, ♻️ 美国自动]}
  - {name: ♻️ 美国自动, type: url-test, include-all: true, tolerance: 20, interval: 60, filter: "(?=.*(广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).*$"}
  - {name: 🇺🇲 美国手动, type: select, include-all: true, filter: "(?=.*(广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).*$"}
  # 家宽组
  - {name: 🏡 家宽节点, type: select, include-all: true, filter: "(?=.*(家宽|家庭)).*$"}
  # 低倍组
  - {name: 🧑‍🦽 低倍节点, type: select, proxies: [🇭🇰 低倍-香港负载, 🇹🇼 低倍-台湾负载, 🇯🇵 低倍-日本负载, 🇸🇬 低倍-新加坡负载, 🇺🇸 低倍-美国负载, 📦 低倍-其他手动, ]}
  # 轮询式负载均衡（多节点分摊流量，适合多节点带宽叠加）
  - {name: 🇭🇰 低倍-香港负载, type: load-balance, include-all: true, interval: 60, strategy: round-robin, persist: true, filter: "(?=.*(0.8|0.5|0.5倍|0.5x|0.1|0.01))(?=.*(广港|香港|HK|Hong Kong|🇭🇰|HongKong)).*$"}
  - {name: 🇹🇼 低倍-台湾负载, type: load-balance, include-all: true, interval: 60, strategy: round-robin, persist: true, filter: "(?=.*(0.8|0.5|0.5倍|0.5x|0.1|0.01))(?=.*(广台|台湾|台灣|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan)).*$"}
  - {name: 🇯🇵 低倍-日本负载, type: load-balance, include-all: true, interval: 60, strategy: round-robin, persist: true, filter: "(?=.*(0.8|0.5|0.5倍|0.5x|0.1|0.01))(?=.*(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)).*$"}
  - {name: 🇸🇬 低倍-新加坡负载, type: load-balance, include-all: true, interval: 60, strategy: round-robin, persist: true, filter: "(?=.*(0.8|0.5|0.5倍|0.5x|0.1|0.01))(?=.*(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)).*$"}
  - {name: 🇺🇸 低倍-美国负载, type: load-balance, include-all: true, interval: 60, strategy: round-robin, persist: true, filter: "(?=.*(0.8|0.5|0.5倍|0.5x|0.1|0.01))(?=.*(广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).*$"}
  - {name: 📦 低倍-其他手动, type: select, include-all: true, filter: "(?=.*(0.8|0.5|0.5倍|0.5x|0.1|0.01))^((?!.*(广港|香港|HK|Hong Kong|🇭🇰|HongKong|广台|台湾|台灣|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan|广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|广新|新加坡|SG|坡|新加坡|🇸🇬|Singapore|广美|US|美国|纽约|波特兰|达拉斯|俄勒|凤凰城|费利蒙|洛杉|圣何塞|圣克拉|西雅|芝加|🇺🇸|United States)).)*$"}
  # 全部组
  - {name: ♻️ 全部自动, type: url-test, include-all: true, tolerance: 20, interval: 60, filter: "^((?!(Direct|Reject)).)*$"}
  - {name: 🌐 全部手动, type: select, include-all: true}
# 规则匹配（rules）
rules:
  - RULE-SET,adblock_domain,广告拦截
  - DOMAIN-SUFFIX,xuedingtoken.com,Direct
  - DOMAIN-SUFFIX,ubits.club,Direct
  - DOMAIN-SUFFIX,ptcafe.club,Direct
  - DOMAIN-SUFFIX,paypal-mktg.com,PayPal
  - DOMAIN-SUFFIX,paypal,PayPal
  - RULE-SET,private_ip,Direct,no-resolve
  - RULE-SET,private_domain,Direct
  - RULE-SET,paypal_domain,PayPal
  - DOMAIN-SUFFIX,qichiyu.com,默认代理
  - RULE-SET,proxylite,默认代理
  - RULE-SET,ai,AI
  - RULE-SET,github_domain,GitHub
  - RULE-SET,tmdb_domain,TMDB
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,GoogleFCM_domain,Google
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,onedrive_domain,Microsoft
  - RULE-SET,microsoft_domain,Microsoft
  - RULE-SET,apple-cn_domain,Direct
  - RULE-SET,apple_domain,Apple
  - RULE-SET,apple_ip,Apple,no-resolve
  - RULE-SET,tiktok_domain,TikTok
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,netflix_ip,NETFLIX,no-resolve
  - RULE-SET,steam_domain,Steam
  - RULE-SET,epicgames_domain,Game
  - RULE-SET,origin_domain,Game
  - RULE-SET,sony_domain,Game
  - RULE-SET,nintendo_domain,Game
  - RULE-SET,geolocation-!cn,默认代理
  - RULE-SET,cn_domain,Direct
  - RULE-SET,cn_ip,Direct
  - MATCH,漏网之鱼
# 规则集
## type：可选http/file/inline  behavior：可选domain/ipcidr/classical format：可选yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  fakeipfilter_domain: {<<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  private_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/rules/proxy.list"}
  ai: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  GoogleFCM_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs"}
  github_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  apple-cn_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  tmdb_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tmdb.mrs"}
  steam_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"}
  nintendo_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/nintendo.mrs"}
  sony_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/sony.mrs"}
  origin_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/origin.mrs"}
  epicgames_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/epicgames.mrs"}
  private_ip: {<<: *ip, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
  adblock_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs"}
  adblock_domain: { <<: *domain, url: "https://gh.xy96.de5.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/adguard.mrs"}
